//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Logs.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trace
    {
        public int ID { get; set; }
        public string AppName { get; set; }
        public Nullable<short> TraceLevel { get; set; }
        public Nullable<short> TraceType { get; set; }
        public string Message { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    }
}
