USE [master]
GO

/****** Object:  Database [WS_Mart]    Script Date: 8/13/2015 9:51:26 AM ******/
CREATE DATABASE [WS_Mart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WS_Mart', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WS_Mart.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WS_Mart_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\WS_Mart_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WS_Mart] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WS_Mart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WS_Mart] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WS_Mart] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WS_Mart] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WS_Mart] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WS_Mart] SET ARITHABORT OFF 
GO

ALTER DATABASE [WS_Mart] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WS_Mart] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WS_Mart] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WS_Mart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WS_Mart] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WS_Mart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WS_Mart] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WS_Mart] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WS_Mart] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WS_Mart] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WS_Mart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WS_Mart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WS_Mart] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WS_Mart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WS_Mart] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WS_Mart] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WS_Mart] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WS_Mart] SET RECOVERY FULL 
GO

ALTER DATABASE [WS_Mart] SET  MULTI_USER 
GO

ALTER DATABASE [WS_Mart] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WS_Mart] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WS_Mart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WS_Mart] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WS_Mart] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WS_Mart] SET  READ_WRITE 
GO

