//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessCategory
    {
        public BusinessCategory()
        {
            this.BusinessCategory1 = new HashSet<BusinessCategory>();
            this.BusinessCategoryLinks = new HashSet<BusinessCategoryLink>();
            this.BusinessPersons = new HashSet<BusinessPerson>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
    
        public virtual ICollection<BusinessCategory> BusinessCategory1 { get; set; }
        public virtual BusinessCategory BusinessCategory2 { get; set; }
        public virtual ICollection<BusinessCategoryLink> BusinessCategoryLinks { get; set; }
        public virtual ICollection<BusinessPerson> BusinessPersons { get; set; }
    }
}
