//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAdress
    {
        public PersonAdress()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BusinessPersonID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public Nullable<int> CityID { get; set; }
        public string PinCode { get; set; }
        public Nullable<bool> PrimaryFlag { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string UpdateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserID { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
