//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Orders = new HashSet<Order>();
            this.ProductDetails = new HashSet<ProductDetail>();
            this.ProductVarients = new HashSet<ProductVarient>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BusinessPersonID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Details { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<short> DeliveryDays { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
    
        public virtual BusinessPerson BusinessPerson { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        public virtual ICollection<ProductVarient> ProductVarients { get; set; }
    }
}
