//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
        public Nullable<System.DateTime> CreaetDateTime { get; set; }
        public string CreateUserID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
